### ISSUE TITLE
Optional To-Do

### ISSUE THREAD

**Issue by Pandaqi** [Pandaqi/Into-My-Arms#1]
**The itch.io page**
- [ ] I don't know about the green background color. It's a bit too much, reduces readability. Can I gradient to a lighter green color somehow?
- [ ] Add alternative trailer that actually shows gameplay (and has original soundtrack)
- [ ] Reduce number of screenshots, instead create a GIF of the gameplay
- [ ] Do we need to start the page with story? Or should I just immediately start with what the game's about?
- [ ] Perhaps add sparkles to the purple background (like in the actual game)

**Visual Polishing**
- [ ] Make a better "exclamation mark" for when you lose the level
- [ ] Make the intro/outro drawings much cleaner and more detailed (now they look like very rough sketches that still need to be turned into the final product)
  - [ ] Make color of outline match object (now it's all just this beige color)
  - [ ] There's a difference between a "sketchy style" and "bad drawing" - I should learn that difference someday. (I could neatly close all outlines and make sure I don't color outside the lines, but that would be boring. I'm looking for a style somewhere in between.)
   - [ ] I forgot there would be text underneath the image, which means it's now cut off in weird places. Either make images fullscreen, or change drawing to account for text.
- [ ] Also resize **sliders** and **checkbox** in the interface
- [ ] Add mask to tiles => color the X, Y and Z axis with a different gradient. This is very useful to see the location of a tile. (With the current isometric view, it's easy to think a tile is right next to you, when it's actually two levels lower or something)
- [ ] Use different gradients on background of levels (and make them transition when camera moves) (instead of just the default blue one)

**New/extra mechanics and systems**
- [ ] FENCES; create separate grid which only contains the connection between two points (fences are always on the edge)
- [ ] Check performance for mobile. (Desktop is more than fine.)
- [ ] Multiple interactive objects: allow different parameters per object, instead of only per color
- [ ] Actually show proper reflections in the mirror (correct angle => angle info is transferred during light path seeking)
- [ ] Trampolines (with fixed destinations?)
- [ ] Ropes you need to cut
- [ ] Try lights + light shader again (instead of "fake" lighting I implemented myself in the current version)
- [ ] Water?

**Small bugs**
- [x] If you press buttons really fast (both mobile and desktop), sometimes it glitches: position visually and position in code gets misplaced. Solution: temporarily deactivate button (once pressed) for 100ms or so?
- [x] Blocking objects: moving objects don't update their transparency; sometimes really hard to see something

**Level inaccuracies**
*  Level 5 has an "easy" solution: fall from red platform (when it's still high in the air). Most people who tested the game didn't come near this solution at all, but hey, can't take any chances.
*  Level 8 doesn't absolutely require you to allow your cubito to be pushed OFF a platform. I really want to use this new mechanic, to require players to think more out of the box.
*  Level 13 has a relatively easy solution: if the red platform is activated, and you just make sure you don't trigger any mirrors, you can make one player stand on the red platform and another falls from the floor above. (This is about halfway the usual steps required to solve this puzzle.)

I do notice an interesting trend in the puzzles: you often have to retrace your steps, but in a different way the second time. For example, you make player A move towards a certain switch. Once pressed, it must follow the same path again, but because something has changed, it suddenly leads to a solution!

**Comment by Pandaqi** [comment]
Don't have time to solve these issues before game jam ends. Have copied them to a separate to-do list for a possible version 2.0 of the game.
